FROM openjdk:11-jdk-slim AS builder

RUN apt-get update && apt-get install -y maven

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY . .

RUN mvn package -DskipTests

FROM openjdk:11-jre-slim

WORKDIR /app

COPY --from=builder /app/target/*.jar app/test.jar

EXPOSE 8082

ENTRYPOINT [ "java", "-jar", "app/test.jar" ]
