FROM node:14-alpine AS build

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de package.json et package-lock.json
COPY package*.json ./
COPY yarn.lock ./

# Installer les dépendances
RUN yarn install

# Copier le reste des fichiers de l'application
COPY . .

# Build de l'application React
RUN yarn build

# Utiliser l'image de base légère nginx pour servir l'application
FROM nginx:alpine

# Copier les fichiers de build de l'application React depuis l'étape précédente
COPY --from=build /app/build /usr/share/nginx/html

# Exposer le port 80 pour le trafic HTTP
EXPOSE 80

# Commande par défaut pour démarrer NGINX lors du lancement du conteneur
CMD ["nginx", "-g", "daemon off;"]
